import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "ru" | "kz" | "en" | "zh" | "az";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  ru: {
    // Navbar
    "nav.home": "Главная",
    "nav.rooms": "Номера",
    "nav.amenities": "Услуги",
    "nav.about": "О нас",
    "nav.testimonials": "Отзывы",
    "nav.restaurant": "Ресторан Берлин",
    "nav.sports": "Спортивным командам",
    "nav.conference": "Конференц-зал",
    "nav.offices": "Аренда офисов",
    "nav.book": "Забронировать",
    
    // Hero
    "hero.title": "Кызыл Жар",
    "hero.subtitle": "Изысканный отдых в сердце города",
    "hero.checkin": "Заезд",
    "hero.checkout": "Выезд",
    "hero.guests": "Гости",
    "hero.guest": "гость",
    "hero.guests_plural": "гостей",
    "hero.check_availability": "Проверить наличие",
    "hero.select_date": "Выберите дату",
    
    // About
    "about.title": "Добро пожаловать в Кызыл Жар",
    "about.subtitle": "Где роскошь встречается с казахстанским гостеприимством",
    "about.heritage.title": "Наследие",
    "about.heritage.desc": "Более 15 лет мы создаём незабываемые впечатления для наших гостей, сохраняя традиции казахстанского гостеприимства",
    "about.excellence.title": "Превосходство",
    "about.excellence.desc": "Каждая деталь продумана до мелочей. От постельного белья премиум-класса до изысканной кухни нашего ресторана",
    "about.location.title": "Расположение",
    "about.location.desc": "Стратегическое расположение в самом сердце города с легким доступом к деловому центру и культурным достопримечательностям",
    "about.stats.rooms": "Номеров",
    "about.stats.guests": "Довольных гостей",
    "about.stats.rating": "Рейтинг",
    "about.stats.experience": "Лет опыта",
    
    // Rooms
    "rooms.title": "Наши номера",
    "rooms.subtitle": "Выберите идеальный номер для вашего комфортного пребывания",
    "rooms.from": "от",
    "rooms.night": "ночь",
    "rooms.details": "Подробнее",
    "rooms.lux.name": "Люкс",
    "rooms.lux.desc": "Просторный номер с панорамным видом, гостиной зоной и премиальными удобствами",
    "rooms.deluxe.name": "Делюкс",
    "rooms.deluxe.desc": "Элегантный номер повышенной комфортности с рабочей зоной и мини-баром",
    "rooms.premium.name": "Премиум",
    "rooms.premium.desc": "Стильный номер с современным дизайном и всеми необходимыми удобствами",
    "rooms.standard.name": "Стандарт",
    "rooms.standard.desc": "Уютный номер со всем необходимым для комфортного отдыха",
    "rooms.econom_plus.name": "Эконом+",
    "rooms.econom_plus.desc": "Комфортный номер по доступной цене с улучшенными удобствами",
    "rooms.econom.name": "Эконом",
    "rooms.econom.desc": "Чистый и уютный номер для экономного путешественника",
    
    // Amenities
    "amenities.title": "Удобства и услуги",
    "amenities.subtitle": "Всё для вашего комфорта",
    "amenities.parking": "Парковка",
    "amenities.parking.desc": "Охраняемая парковка 24/7",
    "amenities.restaurant": "Ресторан",
    "amenities.restaurant.desc": "Изысканная кухня",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Высокоскоростной интернет",
    "amenities.taxi": "Такси",
    "amenities.taxi.desc": "Трансфер по городу",
    "amenities.spa": "Спа",
    "amenities.spa.desc": "Релакс и массаж",
    "amenities.pool": "Бассейн",
    "amenities.pool.desc": "Крытый бассейн",
    "amenities.coffee": "Кофейня",
    "amenities.coffee.desc": "Свежий кофе",
    "amenities.business": "Бизнес-центр",
    "amenities.business.desc": "Для деловых встреч",
    
    // Testimonials
    "testimonials.title": "Отзывы гостей",
    "testimonials.subtitle": "Что говорят о нас",
    
    // Restaurant Berlin
    "restaurant.title": "Ресторан Берлин",
    "restaurant.subtitle": "Изысканная европейская кухня в сердце Казахстана",
    "restaurant.description": "Погрузитесь в атмосферу изысканной европейской кухни. Наш шеф-повар создаёт уникальные блюда, сочетающие немецкие традиции и современные кулинарные тенденции.",
    "restaurant.hours": "Время работы",
    "restaurant.hours.breakfast": "Завтрак: 07:00 - 10:00",
    "restaurant.hours.lunch": "Обед: 12:00 - 15:00",
    "restaurant.hours.dinner": "Ужин: 18:00 - 23:00",
    "restaurant.reserve": "Забронировать столик",
    "restaurant.menu": "Меню",
    "restaurant.banquet": "Банкетный зал",
    "restaurant.banquet.desc": "Идеальное место для торжеств до 100 гостей",
    
    // Sports Teams
    "sports.title": "Для спортивных команд",
    "sports.subtitle": "Специальные условия для профессиональных спортсменов",
    "sports.description": "Мы понимаем потребности спортивных команд. Предлагаем специальные цены, адаптированное питание и удобства для тренировок.",
    "sports.hockey": "Хоккейные команды",
    "sports.hockey.desc": "Специальные условия для хоккеистов",
    "sports.football": "Футбольные команды",
    "sports.football.desc": "Размещение для футбольных клубов",
    "sports.other": "Другие виды спорта",
    "sports.other.desc": "Индивидуальный подход к каждой команде",
    "sports.discount": "скидка",
    "sports.contact": "Связаться с менеджером",
    "sports.features.nutrition": "Спортивное питание",
    "sports.features.schedule": "Гибкий график питания",
    "sports.features.transport": "Групповой трансфер",
    "sports.features.meeting": "Комнаты для собраний",
    
    // Conference
    "conference.title": "Конференц-зал",
    "conference.subtitle": "Современное пространство для ваших мероприятий",
    "conference.description": "Полностью оборудованный конференц-зал для проведения семинаров, презентаций и деловых встреч.",
    "conference.capacity": "Вместимость",
    "conference.capacity.value": "до 150 человек",
    "conference.equipment": "Оборудование",
    "conference.equipment.projector": "Проектор и экран",
    "conference.equipment.sound": "Звуковая система",
    "conference.equipment.wifi": "Высокоскоростной Wi-Fi",
    "conference.equipment.climate": "Климат-контроль",
    "conference.pricing": "Стоимость",
    "conference.pricing.hour": "в час",
    "conference.pricing.day": "полный день",
    "conference.book": "Забронировать зал",
    
    // Offices
    "offices.title": "Аренда офисов",
    "offices.subtitle": "Готовые офисные помещения на 2-м этаже",
    "offices.description": "Современные офисные пространства в престижном месте. Полностью готовы к работе с первого дня.",
    "offices.features.furniture": "Меблированные офисы",
    "offices.features.internet": "Высокоскоростной интернет",
    "offices.features.security": "Круглосуточная охрана",
    "offices.features.parking": "Парковка для сотрудников",
    "offices.features.cleaning": "Уборка включена",
    "offices.features.utilities": "Коммунальные услуги включены",
    "offices.sizes": "Доступные площади",
    "offices.size.small": "Малый офис (15-25 м²)",
    "offices.size.medium": "Средний офис (30-50 м²)",
    "offices.size.large": "Большой офис (60-100 м²)",
    "offices.from": "от",
    "offices.month": "мес",
    "offices.contact": "Узнать подробнее",
    
    // Footer
    "footer.contact": "Контакты",
    "footer.links": "Быстрые ссылки",
    "footer.social": "Социальные сети",
    "footer.hours": "Часы работы",
    "footer.address": "г. Петропавловск, ул. Конституции 38",
    "footer.reception": "Ресепшн работает круглосуточно",
    "footer.rights": "Все права защищены",
  },
  kz: {
    // Navbar
    "nav.home": "Басты бет",
    "nav.rooms": "Бөлмелер",
    "nav.amenities": "Қызметтер",
    "nav.about": "Біз туралы",
    "nav.testimonials": "Пікірлер",
    "nav.restaurant": "Берлин мейрамханасы",
    "nav.sports": "Спорт командаларына",
    "nav.conference": "Конференц-зал",
    "nav.offices": "Кеңсе жалдау",
    "nav.book": "Брондау",
    
    // Hero
    "hero.title": "Қызыл Жар",
    "hero.subtitle": "Қала жүрегіндегі сәнді демалыс",
    "hero.checkin": "Келу",
    "hero.checkout": "Кету",
    "hero.guests": "Қонақтар",
    "hero.guest": "қонақ",
    "hero.guests_plural": "қонақ",
    "hero.check_availability": "Бос орынды тексеру",
    "hero.select_date": "Күнді таңдаңыз",
    
    // About
    "about.title": "Қызыл Жарға қош келдіңіз",
    "about.subtitle": "Сәнділік пен қазақ қонақжайлылығы қосылған жер",
    "about.heritage.title": "Мұра",
    "about.heritage.desc": "15 жылдан астам уақыт бойы қазақ қонақжайлылық дәстүрін сақтай отырып, қонақтарымызға ұмытылмас әсер қалдырамыз",
    "about.excellence.title": "Керемет",
    "about.excellence.desc": "Әрбір бөлшек ойластырылған. Премиум төсек-орындан бастап мейрамхананың таңдаулы тағамдарына дейін",
    "about.location.title": "Орналасуы",
    "about.location.desc": "Іскерлік орталық пен мәдени орындарға оңай қол жетімді қала жүрегінде стратегиялық орналасу",
    "about.stats.rooms": "Бөлмелер",
    "about.stats.guests": "Риза қонақтар",
    "about.stats.rating": "Рейтинг",
    "about.stats.experience": "Тәжірибе жылдары",
    
    // Rooms
    "rooms.title": "Біздің бөлмелер",
    "rooms.subtitle": "Ыңғайлы болу үшін тамаша бөлмені таңдаңыз",
    "rooms.from": "бастап",
    "rooms.night": "түн",
    "rooms.details": "Толығырақ",
    "rooms.lux.name": "Люкс",
    "rooms.lux.desc": "Панорамалық көріністі, қонақ бөлмесі және премиум ыңғайлылықтары бар кең бөлме",
    "rooms.deluxe.name": "Делюкс",
    "rooms.deluxe.desc": "Жұмыс аймағы мен мини-бары бар жоғары комфортты талғампаз бөлме",
    "rooms.premium.name": "Премиум",
    "rooms.premium.desc": "Заманауи дизайны және барлық қажетті ыңғайлылықтары бар стильді бөлме",
    "rooms.standard.name": "Стандарт",
    "rooms.standard.desc": "Жайлы демалыс үшін барлық қажеттісі бар жайлы бөлме",
    "rooms.econom_plus.name": "Эконом+",
    "rooms.econom_plus.desc": "Жақсартылған ыңғайлылықтары бар қолжетімді бағадағы жайлы бөлме",
    "rooms.econom.name": "Эконом",
    "rooms.econom.desc": "Үнемді саяхатшыға арналған таза және жайлы бөлме",
    
    // Amenities
    "amenities.title": "Ыңғайлылықтар мен қызметтер",
    "amenities.subtitle": "Сіздің жайлылығыңыз үшін барлығы",
    "amenities.parking": "Автотұрақ",
    "amenities.parking.desc": "24/7 қорғалған автотұрақ",
    "amenities.restaurant": "Мейрамхана",
    "amenities.restaurant.desc": "Таңдаулы ас",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Жоғары жылдамдықты интернет",
    "amenities.taxi": "Такси",
    "amenities.taxi.desc": "Қала бойынша трансфер",
    "amenities.spa": "Спа",
    "amenities.spa.desc": "Демалыс және массаж",
    "amenities.pool": "Бассейн",
    "amenities.pool.desc": "Жабық бассейн",
    "amenities.coffee": "Кофехана",
    "amenities.coffee.desc": "Жаңа кофе",
    "amenities.business": "Бизнес-орталық",
    "amenities.business.desc": "Іскерлік кездесулер үшін",
    
    // Testimonials
    "testimonials.title": "Қонақтар пікірлері",
    "testimonials.subtitle": "Біз туралы не айтады",
    
    // Restaurant Berlin
    "restaurant.title": "Берлин мейрамханасы",
    "restaurant.subtitle": "Қазақстан жүрегіндегі таңдаулы еуропалық ас",
    "restaurant.description": "Таңдаулы еуропалық ас атмосферасына еніңіз. Біздің бас аспазшы неміс дәстүрлері мен заманауи аспаздық трендтерді біріктіретін бірегей тағамдар жасайды.",
    "restaurant.hours": "Жұмыс уақыты",
    "restaurant.hours.breakfast": "Таңғы ас: 07:00 - 10:00",
    "restaurant.hours.lunch": "Түскі ас: 12:00 - 15:00",
    "restaurant.hours.dinner": "Кешкі ас: 18:00 - 23:00",
    "restaurant.reserve": "Үстел брондау",
    "restaurant.menu": "Мәзір",
    "restaurant.banquet": "Банкет залы",
    "restaurant.banquet.desc": "100 қонаққа дейін мерекелер үшін тамаша орын",
    
    // Sports Teams
    "sports.title": "Спорт командаларына",
    "sports.subtitle": "Кәсіби спортшыларға арнайы шарттар",
    "sports.description": "Біз спорт командаларының қажеттіліктерін түсінеміз. Арнайы бағалар, бейімделген тамақтану және жаттығу ыңғайлылықтарын ұсынамыз.",
    "sports.hockey": "Хоккей командалары",
    "sports.hockey.desc": "Хоккейшілерге арнайы шарттар",
    "sports.football": "Футбол командалары",
    "sports.football.desc": "Футбол клубтарын орналастыру",
    "sports.other": "Басқа спорт түрлері",
    "sports.other.desc": "Әр командаға жеке көзқарас",
    "sports.discount": "жеңілдік",
    "sports.contact": "Менеджермен байланысу",
    "sports.features.nutrition": "Спорттық тамақтану",
    "sports.features.schedule": "Икемді тамақтану кестесі",
    "sports.features.transport": "Топтық трансфер",
    "sports.features.meeting": "Жиналыс бөлмелері",
    
    // Conference
    "conference.title": "Конференц-зал",
    "conference.subtitle": "Іс-шараларыңыз үшін заманауи кеңістік",
    "conference.description": "Семинарлар, презентациялар және іскерлік кездесулер өткізуге арналған толық жабдықталған конференц-зал.",
    "conference.capacity": "Сыйымдылығы",
    "conference.capacity.value": "150 адамға дейін",
    "conference.equipment": "Жабдық",
    "conference.equipment.projector": "Проектор және экран",
    "conference.equipment.sound": "Дыбыс жүйесі",
    "conference.equipment.wifi": "Жоғары жылдамдықты Wi-Fi",
    "conference.equipment.climate": "Климат-бақылау",
    "conference.pricing": "Құны",
    "conference.pricing.hour": "сағатына",
    "conference.pricing.day": "толық күн",
    "conference.book": "Залды брондау",
    
    // Offices
    "offices.title": "Кеңсе жалдау",
    "offices.subtitle": "2-ші қабаттағы дайын кеңсе үй-жайлары",
    "offices.description": "Беделді жердегі заманауи кеңсе кеңістіктері. Бірінші күннен жұмысқа толық дайын.",
    "offices.features.furniture": "Жиһазды кеңселер",
    "offices.features.internet": "Жоғары жылдамдықты интернет",
    "offices.features.security": "Тәулік бойы күзет",
    "offices.features.parking": "Қызметкерлерге автотұрақ",
    "offices.features.cleaning": "Тазалау кіреді",
    "offices.features.utilities": "Коммуналдық қызметтер кіреді",
    "offices.sizes": "Қолжетімді аудандар",
    "offices.size.small": "Шағын кеңсе (15-25 м²)",
    "offices.size.medium": "Орташа кеңсе (30-50 м²)",
    "offices.size.large": "Үлкен кеңсе (60-100 м²)",
    "offices.from": "бастап",
    "offices.month": "ай",
    "offices.contact": "Толығырақ білу",
    
    // Footer
    "footer.contact": "Байланыс",
    "footer.links": "Жылдам сілтемелер",
    "footer.social": "Әлеуметтік желілер",
    "footer.hours": "Жұмыс уақыты",
    "footer.address": "Петропавл қ., Конституция к. 38",
    "footer.reception": "Ресепшн тәулік бойы жұмыс істейді",
    "footer.rights": "Барлық құқықтар қорғалған",
  },
  en: {
    // Navbar
    "nav.home": "Home",
    "nav.rooms": "Rooms",
    "nav.amenities": "Amenities",
    "nav.about": "About",
    "nav.testimonials": "Reviews",
    "nav.restaurant": "Restaurant Berlin",
    "nav.sports": "Sports Teams",
    "nav.conference": "Conference Hall",
    "nav.offices": "Office Rental",
    "nav.book": "Book Now",
    
    // Hero
    "hero.title": "Kyzyl Zhar",
    "hero.subtitle": "Exquisite relaxation in the heart of the city",
    "hero.checkin": "Check-in",
    "hero.checkout": "Check-out",
    "hero.guests": "Guests",
    "hero.guest": "guest",
    "hero.guests_plural": "guests",
    "hero.check_availability": "Check Availability",
    "hero.select_date": "Select date",
    
    // About
    "about.title": "Welcome to Kyzyl Zhar",
    "about.subtitle": "Where luxury meets Kazakh hospitality",
    "about.heritage.title": "Heritage",
    "about.heritage.desc": "For over 15 years, we have been creating unforgettable experiences for our guests while preserving the traditions of Kazakh hospitality",
    "about.excellence.title": "Excellence",
    "about.excellence.desc": "Every detail is carefully thought out. From premium linens to the exquisite cuisine of our restaurant",
    "about.location.title": "Location",
    "about.location.desc": "Strategic location in the very heart of the city with easy access to the business center and cultural attractions",
    "about.stats.rooms": "Rooms",
    "about.stats.guests": "Happy Guests",
    "about.stats.rating": "Rating",
    "about.stats.experience": "Years of Experience",
    
    // Rooms
    "rooms.title": "Our Rooms",
    "rooms.subtitle": "Choose the perfect room for your comfortable stay",
    "rooms.from": "from",
    "rooms.night": "night",
    "rooms.details": "Details",
    "rooms.lux.name": "Luxury Suite",
    "rooms.lux.desc": "Spacious room with panoramic views, living area and premium amenities",
    "rooms.deluxe.name": "Deluxe",
    "rooms.deluxe.desc": "Elegant room with enhanced comfort, work area and mini-bar",
    "rooms.premium.name": "Premium",
    "rooms.premium.desc": "Stylish room with modern design and all necessary amenities",
    "rooms.standard.name": "Standard",
    "rooms.standard.desc": "Cozy room with everything you need for a comfortable stay",
    "rooms.econom_plus.name": "Economy+",
    "rooms.econom_plus.desc": "Comfortable room at an affordable price with enhanced amenities",
    "rooms.econom.name": "Economy",
    "rooms.econom.desc": "Clean and cozy room for the budget traveler",
    
    // Amenities
    "amenities.title": "Amenities & Services",
    "amenities.subtitle": "Everything for your comfort",
    "amenities.parking": "Parking",
    "amenities.parking.desc": "24/7 secure parking",
    "amenities.restaurant": "Restaurant",
    "amenities.restaurant.desc": "Fine dining",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "High-speed internet",
    "amenities.taxi": "Taxi",
    "amenities.taxi.desc": "City transfer",
    "amenities.spa": "Spa",
    "amenities.spa.desc": "Relaxation & massage",
    "amenities.pool": "Pool",
    "amenities.pool.desc": "Indoor pool",
    "amenities.coffee": "Coffee Shop",
    "amenities.coffee.desc": "Fresh coffee",
    "amenities.business": "Business Center",
    "amenities.business.desc": "For business meetings",
    
    // Testimonials
    "testimonials.title": "Guest Reviews",
    "testimonials.subtitle": "What they say about us",
    
    // Restaurant Berlin
    "restaurant.title": "Restaurant Berlin",
    "restaurant.subtitle": "Exquisite European cuisine in the heart of Kazakhstan",
    "restaurant.description": "Immerse yourself in the atmosphere of exquisite European cuisine. Our chef creates unique dishes combining German traditions and modern culinary trends.",
    "restaurant.hours": "Opening Hours",
    "restaurant.hours.breakfast": "Breakfast: 07:00 - 10:00",
    "restaurant.hours.lunch": "Lunch: 12:00 - 15:00",
    "restaurant.hours.dinner": "Dinner: 18:00 - 23:00",
    "restaurant.reserve": "Reserve a Table",
    "restaurant.menu": "Menu",
    "restaurant.banquet": "Banquet Hall",
    "restaurant.banquet.desc": "Perfect venue for celebrations up to 100 guests",
    
    // Sports Teams
    "sports.title": "For Sports Teams",
    "sports.subtitle": "Special conditions for professional athletes",
    "sports.description": "We understand the needs of sports teams. We offer special prices, adapted nutrition and training facilities.",
    "sports.hockey": "Hockey Teams",
    "sports.hockey.desc": "Special conditions for hockey players",
    "sports.football": "Football Teams",
    "sports.football.desc": "Accommodation for football clubs",
    "sports.other": "Other Sports",
    "sports.other.desc": "Individual approach to each team",
    "sports.discount": "discount",
    "sports.contact": "Contact Manager",
    "sports.features.nutrition": "Sports Nutrition",
    "sports.features.schedule": "Flexible Meal Schedule",
    "sports.features.transport": "Group Transfer",
    "sports.features.meeting": "Meeting Rooms",
    
    // Conference
    "conference.title": "Conference Hall",
    "conference.subtitle": "Modern space for your events",
    "conference.description": "Fully equipped conference hall for seminars, presentations and business meetings.",
    "conference.capacity": "Capacity",
    "conference.capacity.value": "up to 150 people",
    "conference.equipment": "Equipment",
    "conference.equipment.projector": "Projector & screen",
    "conference.equipment.sound": "Sound system",
    "conference.equipment.wifi": "High-speed Wi-Fi",
    "conference.equipment.climate": "Climate control",
    "conference.pricing": "Pricing",
    "conference.pricing.hour": "per hour",
    "conference.pricing.day": "full day",
    "conference.book": "Book Hall",
    
    // Offices
    "offices.title": "Office Rental",
    "offices.subtitle": "Ready-to-use office spaces on the 2nd floor",
    "offices.description": "Modern office spaces in a prestigious location. Fully ready to work from day one.",
    "offices.features.furniture": "Furnished offices",
    "offices.features.internet": "High-speed internet",
    "offices.features.security": "24/7 security",
    "offices.features.parking": "Employee parking",
    "offices.features.cleaning": "Cleaning included",
    "offices.features.utilities": "Utilities included",
    "offices.sizes": "Available Sizes",
    "offices.size.small": "Small office (15-25 m²)",
    "offices.size.medium": "Medium office (30-50 m²)",
    "offices.size.large": "Large office (60-100 m²)",
    "offices.from": "from",
    "offices.month": "mo",
    "offices.contact": "Learn More",
    
    // Footer
    "footer.contact": "Contact",
    "footer.links": "Quick Links",
    "footer.social": "Social Media",
    "footer.hours": "Working Hours",
    "footer.address": "38 Constitution St., Petropavlovsk",
    "footer.reception": "Reception works 24/7",
    "footer.rights": "All rights reserved",
  },
  zh: {
    // Navbar
    "nav.home": "首页",
    "nav.rooms": "客房",
    "nav.amenities": "设施",
    "nav.about": "关于我们",
    "nav.testimonials": "评论",
    "nav.restaurant": "柏林餐厅",
    "nav.sports": "运动队",
    "nav.conference": "会议厅",
    "nav.offices": "办公室租赁",
    "nav.book": "预订",
    
    // Hero
    "hero.title": "克孜勒扎尔",
    "hero.subtitle": "城市中心的精致休闲",
    "hero.checkin": "入住",
    "hero.checkout": "退房",
    "hero.guests": "客人",
    "hero.guest": "位客人",
    "hero.guests_plural": "位客人",
    "hero.check_availability": "查询空房",
    "hero.select_date": "选择日期",
    
    // About
    "about.title": "欢迎来到克孜勒扎尔",
    "about.subtitle": "奢华与哈萨克待客之道的完美结合",
    "about.heritage.title": "传承",
    "about.heritage.desc": "15年来，我们在保持哈萨克待客传统的同时，为客人创造难忘的体验",
    "about.excellence.title": "卓越",
    "about.excellence.desc": "每一个细节都经过精心设计。从优质床品到餐厅的精致美食",
    "about.location.title": "位置",
    "about.location.desc": "位于市中心的战略位置，便捷通往商务中心和文化景点",
    "about.stats.rooms": "客房数",
    "about.stats.guests": "满意客人",
    "about.stats.rating": "评分",
    "about.stats.experience": "年经验",
    
    // Rooms
    "rooms.title": "我们的客房",
    "rooms.subtitle": "选择最适合您舒适入住的客房",
    "rooms.from": "起价",
    "rooms.night": "晚",
    "rooms.details": "详情",
    "rooms.lux.name": "豪华套房",
    "rooms.lux.desc": "宽敞的客房，配有全景视野、客厅区域和高级设施",
    "rooms.deluxe.name": "豪华房",
    "rooms.deluxe.desc": "优雅舒适的客房，配有工作区和迷你吧",
    "rooms.premium.name": "高级房",
    "rooms.premium.desc": "现代设计的时尚客房，配备所有必需设施",
    "rooms.standard.name": "标准房",
    "rooms.standard.desc": "舒适的客房，满足您舒适入住的一切需求",
    "rooms.econom_plus.name": "经济+",
    "rooms.econom_plus.desc": "价格实惠、设施升级的舒适客房",
    "rooms.econom.name": "经济房",
    "rooms.econom.desc": "为预算旅行者准备的干净舒适客房",
    
    // Amenities
    "amenities.title": "设施与服务",
    "amenities.subtitle": "一切为您的舒适",
    "amenities.parking": "停车场",
    "amenities.parking.desc": "24/7安全停车",
    "amenities.restaurant": "餐厅",
    "amenities.restaurant.desc": "精致美食",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "高速网络",
    "amenities.taxi": "出租车",
    "amenities.taxi.desc": "城市接送",
    "amenities.spa": "水疗",
    "amenities.spa.desc": "放松与按摩",
    "amenities.pool": "游泳池",
    "amenities.pool.desc": "室内游泳池",
    "amenities.coffee": "咖啡厅",
    "amenities.coffee.desc": "新鲜咖啡",
    "amenities.business": "商务中心",
    "amenities.business.desc": "商务会议",
    
    // Testimonials
    "testimonials.title": "客人评价",
    "testimonials.subtitle": "他们对我们的评价",
    
    // Restaurant Berlin
    "restaurant.title": "柏林餐厅",
    "restaurant.subtitle": "哈萨克斯坦中心的精致欧洲美食",
    "restaurant.description": "沉浸在精致欧洲美食的氛围中。我们的主厨创造独特的菜肴，将德国传统与现代烹饪趋势相结合。",
    "restaurant.hours": "营业时间",
    "restaurant.hours.breakfast": "早餐: 07:00 - 10:00",
    "restaurant.hours.lunch": "午餐: 12:00 - 15:00",
    "restaurant.hours.dinner": "晚餐: 18:00 - 23:00",
    "restaurant.reserve": "预订餐位",
    "restaurant.menu": "菜单",
    "restaurant.banquet": "宴会厅",
    "restaurant.banquet.desc": "可容纳100位客人的完美庆典场所",
    
    // Sports Teams
    "sports.title": "运动队专属",
    "sports.subtitle": "为专业运动员提供特别条件",
    "sports.description": "我们了解运动队的需求。提供特别价格、定制营养和训练设施。",
    "sports.hockey": "冰球队",
    "sports.hockey.desc": "冰球运动员专属条件",
    "sports.football": "足球队",
    "sports.football.desc": "足球俱乐部住宿",
    "sports.other": "其他运动",
    "sports.other.desc": "每支球队的个性化服务",
    "sports.discount": "折扣",
    "sports.contact": "联系经理",
    "sports.features.nutrition": "运动营养",
    "sports.features.schedule": "灵活用餐时间",
    "sports.features.transport": "团队接送",
    "sports.features.meeting": "会议室",
    
    // Conference
    "conference.title": "会议厅",
    "conference.subtitle": "为您的活动提供现代化空间",
    "conference.description": "设备齐全的会议厅，可举办研讨会、演示和商务会议。",
    "conference.capacity": "容量",
    "conference.capacity.value": "最多150人",
    "conference.equipment": "设备",
    "conference.equipment.projector": "投影仪和屏幕",
    "conference.equipment.sound": "音响系统",
    "conference.equipment.wifi": "高速Wi-Fi",
    "conference.equipment.climate": "空调",
    "conference.pricing": "价格",
    "conference.pricing.hour": "每小时",
    "conference.pricing.day": "全天",
    "conference.book": "预订会议厅",
    
    // Offices
    "offices.title": "办公室租赁",
    "offices.subtitle": "二楼即用型办公空间",
    "offices.description": "位于优越地段的现代办公空间。从第一天起即可投入使用。",
    "offices.features.furniture": "配备家具的办公室",
    "offices.features.internet": "高速网络",
    "offices.features.security": "24小时安保",
    "offices.features.parking": "员工停车位",
    "offices.features.cleaning": "包含清洁",
    "offices.features.utilities": "包含水电费",
    "offices.sizes": "可用面积",
    "offices.size.small": "小型办公室 (15-25 m²)",
    "offices.size.medium": "中型办公室 (30-50 m²)",
    "offices.size.large": "大型办公室 (60-100 m²)",
    "offices.from": "起价",
    "offices.month": "月",
    "offices.contact": "了解更多",
    
    // Footer
    "footer.contact": "联系方式",
    "footer.links": "快速链接",
    "footer.social": "社交媒体",
    "footer.hours": "营业时间",
    "footer.address": "彼得罗巴甫洛夫斯克市，宪法街38号",
    "footer.reception": "前台24小时服务",
    "footer.rights": "版权所有",
  },
  az: {
    // Navbar
    "nav.home": "Ana səhifə",
    "nav.rooms": "Otaqlar",
    "nav.amenities": "Xidmətlər",
    "nav.about": "Haqqımızda",
    "nav.testimonials": "Rəylər",
    "nav.restaurant": "Berlin Restoranı",
    "nav.sports": "İdman komandaları",
    "nav.conference": "Konfrans zalı",
    "nav.offices": "Ofis kirayəsi",
    "nav.book": "Rezervasiya",
    
    // Hero
    "hero.title": "Kızıl Jar",
    "hero.subtitle": "Şəhərin mərkəzində zərif istirahət",
    "hero.checkin": "Giriş",
    "hero.checkout": "Çıxış",
    "hero.guests": "Qonaqlar",
    "hero.guest": "qonaq",
    "hero.guests_plural": "qonaq",
    "hero.check_availability": "Mövcudluğu yoxla",
    "hero.select_date": "Tarix seçin",
    
    // About
    "about.title": "Kızıl Jara xoş gəlmisiniz",
    "about.subtitle": "Lüks Qazax qonaqpərvərliyi ilə görüşür",
    "about.heritage.title": "Miras",
    "about.heritage.desc": "15 ildən artıqdır ki, Qazax qonaqpərvərlik ənənələrini qoruyaraq qonaqlarımız üçün unudulmaz təcrübələr yaradırıq",
    "about.excellence.title": "Mükəmməllik",
    "about.excellence.desc": "Hər bir detal düşünülmüşdür. Premium yataq dəstindən restoranımızın zərif mətbəxinə qədər",
    "about.location.title": "Yerləşmə",
    "about.location.desc": "İş mərkəzinə və mədəni yerlərə asan çıxışla şəhərin mərkəzində strateji yerləşmə",
    "about.stats.rooms": "Otaqlar",
    "about.stats.guests": "Razı qonaqlar",
    "about.stats.rating": "Reytinq",
    "about.stats.experience": "İllik təcrübə",
    
    // Rooms
    "rooms.title": "Otaqlarımız",
    "rooms.subtitle": "Rahat qalma üçün ideal otağı seçin",
    "rooms.from": "başlayaraq",
    "rooms.night": "gecə",
    "rooms.details": "Ətraflı",
    "rooms.lux.name": "Lüks",
    "rooms.lux.desc": "Panoramik mənzərəli, qonaq otağı və premium rahatlıqları olan geniş otaq",
    "rooms.deluxe.name": "Deluxe",
    "rooms.deluxe.desc": "İş sahəsi və mini-barı olan yüksək rahatlıqlı zərif otaq",
    "rooms.premium.name": "Premium",
    "rooms.premium.desc": "Müasir dizaynlı və bütün lazımi rahatlıqları olan şık otaq",
    "rooms.standard.name": "Standart",
    "rooms.standard.desc": "Rahat qalmaq üçün hər şeyi olan rahat otaq",
    "rooms.econom_plus.name": "Ekonom+",
    "rooms.econom_plus.desc": "Təkmilləşdirilmiş rahatlıqlarla əlverişli qiymətə rahat otaq",
    "rooms.econom.name": "Ekonom",
    "rooms.econom.desc": "Büdcəli səyahətçi üçün təmiz və rahat otaq",
    
    // Amenities
    "amenities.title": "Rahatlıqlar və xidmətlər",
    "amenities.subtitle": "Rahatlığınız üçün hər şey",
    "amenities.parking": "Parkinq",
    "amenities.parking.desc": "24/7 mühafizəli parkinq",
    "amenities.restaurant": "Restoran",
    "amenities.restaurant.desc": "Zərif mətbəx",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Yüksək sürətli internet",
    "amenities.taxi": "Taksi",
    "amenities.taxi.desc": "Şəhər transferi",
    "amenities.spa": "Spa",
    "amenities.spa.desc": "İstirahət və masaj",
    "amenities.pool": "Hovuz",
    "amenities.pool.desc": "Qapalı hovuz",
    "amenities.coffee": "Kofe dükanı",
    "amenities.coffee.desc": "Təzə qəhvə",
    "amenities.business": "Biznes mərkəzi",
    "amenities.business.desc": "İş görüşləri üçün",
    
    // Testimonials
    "testimonials.title": "Qonaq rəyləri",
    "testimonials.subtitle": "Bizim haqqımızda nə deyirlər",
    
    // Restaurant Berlin
    "restaurant.title": "Berlin Restoranı",
    "restaurant.subtitle": "Qazaxıstanın mərkəzində zərif Avropa mətbəxi",
    "restaurant.description": "Zərif Avropa mətbəxi atmosferinə qərq olun. Aşpazımız alman ənənələri və müasir kulinariya meyllərini birləşdirən unikal yeməklər yaradır.",
    "restaurant.hours": "İş saatları",
    "restaurant.hours.breakfast": "Səhər yeməyi: 07:00 - 10:00",
    "restaurant.hours.lunch": "Nahar: 12:00 - 15:00",
    "restaurant.hours.dinner": "Şam yeməyi: 18:00 - 23:00",
    "restaurant.reserve": "Masa rezerv et",
    "restaurant.menu": "Menyu",
    "restaurant.banquet": "Ziyafət zalı",
    "restaurant.banquet.desc": "100 qonağa qədər bayramlar üçün ideal məkan",
    
    // Sports Teams
    "sports.title": "İdman komandaları üçün",
    "sports.subtitle": "Peşəkar idmançılar üçün xüsusi şərtlər",
    "sports.description": "Biz idman komandalarının ehtiyaclarını başa düşürük. Xüsusi qiymətlər, uyğunlaşdırılmış qidalanma və məşq imkanları təklif edirik.",
    "sports.hockey": "Xokkey komandaları",
    "sports.hockey.desc": "Xokkeyçilər üçün xüsusi şərtlər",
    "sports.football": "Futbol komandaları",
    "sports.football.desc": "Futbol klublarının yerləşdirilməsi",
    "sports.other": "Digər idman növləri",
    "sports.other.desc": "Hər komandaya fərdi yanaşma",
    "sports.discount": "endirim",
    "sports.contact": "Menecerlə əlaqə",
    "sports.features.nutrition": "İdman qidalanması",
    "sports.features.schedule": "Çevik yemək cədvəli",
    "sports.features.transport": "Qrup transferi",
    "sports.features.meeting": "Görüş otaqları",
    
    // Conference
    "conference.title": "Konfrans zalı",
    "conference.subtitle": "Tədbirləriniz üçün müasir məkan",
    "conference.description": "Seminarlar, təqdimatlar və iş görüşləri üçün tam təchiz olunmuş konfrans zalı.",
    "conference.capacity": "Tutum",
    "conference.capacity.value": "150 nəfərə qədər",
    "conference.equipment": "Avadanlıq",
    "conference.equipment.projector": "Proyektor və ekran",
    "conference.equipment.sound": "Səs sistemi",
    "conference.equipment.wifi": "Yüksək sürətli Wi-Fi",
    "conference.equipment.climate": "Klimat nəzarəti",
    "conference.pricing": "Qiymət",
    "conference.pricing.hour": "saatda",
    "conference.pricing.day": "tam gün",
    "conference.book": "Zalı rezerv et",
    
    // Offices
    "offices.title": "Ofis kirayəsi",
    "offices.subtitle": "2-ci mərtəbədə hazır ofis yerləri",
    "offices.description": "Prestijli yerdə müasir ofis məkanları. Birinci gündən işə tam hazırdır.",
    "offices.features.furniture": "Mebelləşdirilmiş ofislər",
    "offices.features.internet": "Yüksək sürətli internet",
    "offices.features.security": "24/7 mühafizə",
    "offices.features.parking": "İşçilər üçün parkinq",
    "offices.features.cleaning": "Təmizlik daxildir",
    "offices.features.utilities": "Kommunal xidmətlər daxildir",
    "offices.sizes": "Mövcud sahələr",
    "offices.size.small": "Kiçik ofis (15-25 m²)",
    "offices.size.medium": "Orta ofis (30-50 m²)",
    "offices.size.large": "Böyük ofis (60-100 m²)",
    "offices.from": "başlayaraq",
    "offices.month": "ay",
    "offices.contact": "Ətraflı öyrən",
    
    // Footer
    "footer.contact": "Əlaqə",
    "footer.links": "Sürətli keçidlər",
    "footer.social": "Sosial şəbəkələr",
    "footer.hours": "İş saatları",
    "footer.address": "Petropavlovsk ş., Konstitusiya küç. 38",
    "footer.reception": "Resepşn 24/7 işləyir",
    "footer.rights": "Bütün hüquqlar qorunur",
  },
};

const languageNames: Record<Language, string> = {
  ru: "Русский",
  kz: "Қазақша",
  en: "English",
  zh: "中文",
  az: "Azərbaycan",
};

const languageFlags: Record<Language, string> = {
  ru: "🇷🇺",
  kz: "🇰🇿",
  en: "🇬🇧",
  zh: "🇨🇳",
  az: "🇦🇿",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export { languageNames, languageFlags };
