import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "ru" | "kz" | "en" | "zh" | "az";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  // =================================================================================================
  // РУССКИЙ (RU)
  // =================================================================================================
  ru: {
    // --- Navigation ---
    "nav.home": "Главная",
    "nav.rooms": "Номера",
    "nav.amenities": "Услуги",
    "nav.about": "О нас",
    "nav.testimonials": "Отзывы",
    "nav.conference": "Конференц-зал",
    "nav.contacts": "Контакты",
    "nav.news": "Новости",
    "nav.book": "Забронировать",
    "nav.restaurant": "Ресторан",
    "nav.sports": "Спорт командам",
    "nav.offices": "Аренда офисов",
    "nav.photoshoots": "Фотосессии",

    // --- Hero ---
    "hero.title": "Кызыл Жар",
    "hero.subtitle": "Изысканный отдых в сердце города",
    "hero.checkin": "Заезд",
    "hero.checkout": "Выезд",
    "hero.guests": "Гости",
    "hero.guest": "гость",
    "hero.guests_plural": "гостей",
    "hero.check_availability": "Проверить наличие",
    "hero.select_date": "Выберите дату",

    // --- About ---
    "about.title": "Добро пожаловать в Кызыл Жар",
    "about.subtitle": "Где роскошь встречается с гостеприимством",
    "about.heritage.title": "Наследие",
    "about.heritage.desc": "Более 15 лет мы создаём незабываемые впечатления.",
    "about.excellence.title": "Превосходство",
    "about.excellence.desc": "Каждая деталь продумана до мелочей.",
    "about.location.title": "Расположение",
    "about.location.desc": "В самом сердце города.",
    "about.stats.rooms": "Номеров",
    "about.stats.guests": "Гостей",
    "about.stats.rating": "Рейтинг",
    "about.stats.experience": "Лет опыта",

    // --- 3D Tour ---
    "tour.label": "ВИРТУАЛЬНАЯ ПРОГУЛКА",
    "tour.title": "3D Тур по отелю",
    "tour.desc": "Окунитесь в атмосферу нашего отеля не выходя из дома.",
    "tour.fullscreen": "На весь экран",
    "tour.open_full": "Открыть 3D тур на весь экран",

    // --- Rooms General ---
    "rooms.title": "Номера и цены",
    "rooms.subtitle": "Выберите идеальный номер для вашего отдыха",
    "rooms.from": "от",
    "rooms.night": "ночь",
    "rooms.details": "Подробнее",
    "rooms.smoking.title": "Правила курения",
    "rooms.smoking.desc": "Курение в номерах строго запрещено.",

    // --- Room Names & Descs (Specific) ---
    "rooms.single_econom.name": "Одноместный эконом",
    "rooms.single_econom.desc": "Компактный номер для бюджетного размещения.",
    "rooms.single_econom_wide.name": "Одноместный эконом с широкой кроватью",
    "rooms.single_econom_wide.desc": "Уютный эконом с увеличенным спальным местом.",
    "rooms.single_two_room.name": "Одноместный Двухкомнатный",
    "rooms.single_two_room.desc": "Просторный номер из двух комнат для одного гостя.",
    "rooms.econom_plus.name": "Эконом плюс",
    "rooms.econom_plus.desc": "Улучшенный эконом с доп. пространством.",
    "rooms.single_standard.name": "Одноместный Стандарт",
    "rooms.single_standard.desc": "Классический номер со всеми удобствами.",
    "rooms.single_semilux.name": "Одноместный Полулюкс",
    "rooms.single_semilux.desc": "Повышенный комфорт для одного гостя.",
    "rooms.double_econom.name": "Двухместный эконом",
    "rooms.double_econom.desc": "Выгодное решение для двоих гостей.",
    "rooms.double_econom_plus.name": "Двухместный эконом+",
    "rooms.double_econom_plus.desc": "Просторный номер с современным дизайном.",
    "rooms.double_standard.name": "Двухместный стандарт",
    "rooms.double_standard.desc": "Комфортный номер с качественным ремонтом.",
    "rooms.triple_econom.name": "Трёхместный эконом",
    "rooms.triple_econom.desc": "Бюджетный вариант для группы из трех человек.",
    "rooms.triple.name": "Трёхместный улучшенный",
    "rooms.triple.desc": "Комфортный номер с тремя спальными местами.",
    "rooms.quadruple_econom.name": "Четырехместный эконом",
    "rooms.quadruple_econom.desc": "Идеально для большой компании или семьи.",
    "rooms.double_semilux.name": "Двухместный полулюкс",
    "rooms.double_semilux.desc": "Стильный номер с зоной отдыха для двоих.",
    "rooms.lux_2room.name": "Двухкомнатный люкс",
    "rooms.lux_2room.desc": "Номер с отдельной спальней и гостиной.",
    "rooms.lux_3room.name": "Трёхкомнатный люкс",
    "rooms.lux_3room.desc": "Королевский размах: три комнаты, максимальный комфорт.",
    "rooms.family_3room.name": "Семейный (3 комнаты)",
    "rooms.family_3room.desc": "Большой семейный номер, удобно для родителей.",
    "rooms.family_2place.name": "Семейный (2 места)",
    "rooms.family_2place.desc": "Уютный семейный номер.",

    // --- Services Page (NEW) ---
    "services.title": "Дополнительные услуги",
    "services.photoshoot.text": "Проведение фотосессий в номерах люкс: 1 час - 15 000 тенге",

    // --- Amenities ---
    "amenities.title": "Удобства",
    "amenities.subtitle": "Всё для вашего комфорта",
    "amenities.parking": "Парковка",
    "amenities.parking.desc": "Охраняемая парковка 24/7",
    "amenities.restaurant": "Ресторан",
    "amenities.restaurant.desc": "Изысканная кухня",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Высокоскоростной интернет",
    "amenities.taxi": "Такси",
    "amenities.taxi.desc": "Трансфер по городу",
    "amenities.spa": "Спа",
    "amenities.spa.desc": "Релакс и отдых",
    "amenities.pool": "Бассейн",
    "amenities.pool.desc": "Крытый бассейн",
    "amenities.coffee": "Кофейня",
    "amenities.coffee.desc": "Свежий кофе",
    "amenities.business": "Бизнес-центр",
    "amenities.business.desc": "Для деловых встреч",

    // --- Sports Section ---
    "sports.title": "Спортивным командам",
    "sports.subtitle": "Специальные условия для профессионалов",
    "sports.description": "Мы понимаем потребности спортивных команд. Предлагаем специальные цены, адаптированное питание и удобства для тренировок.",
    "sports.hockey": "Хоккейные команды",
    "sports.hockey.desc": "Специальные условия для хоккеистов",
    "sports.football": "Футбольные команды",
    "sports.football.desc": "Размещение для футбольных клубов",
    "sports.other": "Другие виды спорта",
    "sports.other.desc": "Индивидуальный подход к каждой команде",
    "sports.discount": "скидка",
    "sports.contact": "Связаться с менеджером",
    "sports.features.nutrition": "Спортивное питание",
    "sports.features.schedule": "Гибкий график питания",
    "sports.features.transport": "Групповой трансфер",
    "sports.features.meeting": "Комнаты для собраний",

    // --- Conference ---
    "conference.title": "Конференц-зал",
    "conference.subtitle": "Пространство для ваших мероприятий",
    "conference.description": "Современный зал для семинаров и тренингов.",
    "conference.capacity": "Вместимость",
    "conference.capacity.value": "до 150 человек",
    "conference.people": "человек",
    "conference.equipment": "Оборудование",
    "conference.equipment.projector": "Проектор и экран",
    "conference.equipment.sound": "Звуковая система",
    "conference.equipment.wifi": "Wi-Fi",
    "conference.equipment.climate": "Кондиционер",
    "conference.pricing": "Стоимость",
    "conference.pricing.hour": "в час",
    "conference.pricing.day": "полный день",
    "conference.book": "Забронировать зал",
    "conference.book.desc": "Свяжитесь с нами для уточнения деталей",
    "conference.gallery": "Галерея",

    // --- News General ---
    "news.title": "Новости",
    "news.subtitle": "События и обновления отеля",
    "news.read_more": "Читать далее",
    "news.category.restaurant": "Ресторан",
    "news.category.hotel": "Отель",
    "news.category.events": "События",
    "news.category.conference": "Конференции",
    "news.category.video": "Видео",

    // --- Specific News Items ---
    "news.2gis.title": "Гостиничный комплекс Кызыл Жар получил премию 2GIS Awards",
    "news.2gis.desc": "Мы рады сообщить, что благодаря вашим отзывам мы стали одними из лучших.",
    "news.promo.title": "ГК Кызыл-Жар: Добро пожаловать!",
    "news.promo.desc": "Добро пожаловать в атмосферу тепла, уюта и гостеприимства гостиничного комплекса.",
    "news.buffet.title": "Открылось кафе «Буфет»",
    "news.buffet.desc": "Приглашаем вас посетить наше новое кафе с обновленным меню и уютным интерьером.",
    "news.welcome.title": "Добро пожаловать в Кызыл Жар",
    "news.welcome.desc": "Уникальное сочетание современного комфорта и традиционного гостеприимства.",
    "news.cozy.title": "Атмосфера тепла и уюта",
    "news.cozy.desc": "Мы создаем условия, в которых каждый гость чувствует себя как дома.",
    "news.photo.title": "Новая фотосессия гостиницы",
    "news.photo.desc": "Взгляните на наш отель по-новому. Обновленная галерея интерьеров холла и номеров.",
    "news.lux317.title": "Люкс 317 для особых гостей",
    "news.lux317.desc": "Эксклюзивный обзор нашего лучшего номера категории Люкс.",

    // --- Contacts ---
    "contacts.title": "Контакты",
    "contacts.subtitle": "Мы всегда на связи",
    "contacts.info.title": "Контактная информация",
    "contacts.address.label": "Адрес",
    "contacts.phone.label": "Телефон",
    "contacts.email.label": "Email",
    "contacts.hours.label": "Режим работы",
    "contacts.form.title": "Напишите нам",
    "contacts.form.name": "Ваше имя",
    "contacts.form.email": "Email",
    "contacts.form.subject": "Тема",
    "contacts.form.message": "Сообщение",
    "contacts.form.send": "Отправить",
    "contacts.map.title": "Мы на карте",

    // --- Footer ---
    "footer.contact": "Контакты",
    "footer.links": "Навигация",
    "footer.hours": "Режим работы",
    "footer.address": "г. Петропавловск, ул. Конституции 54",
    "footer.reception.label": "Ресепшн",
    "footer.reception.value": "Круглосуточно",
    "footer.checkin.label": "Заезд / Выезд",
    "footer.rights": "Все права защищены",
    "footer.privacy": "Политика конфиденциальности",
    "footer.terms": "Условия",
    "footer.description": "Ваш комфорт — наш приоритет.",

    // --- Testimonials ---
    "testimonials.title": "Отзывы",
    "testimonials.subtitle": "Что говорят о нас наши гости",

    // --- Booking ---
    "booking.title": "Бронирование",
    "booking.subtitle": "Мы свяжемся с вами в WhatsApp",
    "booking.name": "Ваше имя",
    "booking.name.placeholder": "Введите имя",
    "booking.room_type": "Номер",
    "booking.select_room": "Выберите номер",
    "booking.send": "Отправить",
    "booking.book_this_room": "Забронировать этот номер",

    // --- Room Amenities List ---
    "room.amenity.single_bed": "Односпальная кровать",
    "room.amenity.double_bed": "Двуспальная кровать",
    "room.amenity.queen_bed": "Кровать Queen-size",
    "room.amenity.king_bed": "Кровать King-size",
    "room.amenity.sofa_bed": "Раскладной диван",
    "room.amenity.hairdryer": "Фен",
    "room.amenity.workspace": "Рабочая зона",
    "room.amenity.bathrobe": "Халат и тапочки",
    "room.amenity.minibar": "Мини-бар",
    "room.amenity.safe": "Сейф",
  },

  // =================================================================================================
  // КАЗАХСКИЙ (KZ)
  // =================================================================================================
  kz: {
    "nav.home": "Басты бет",
    "nav.rooms": "Бөлмелер",
    "nav.amenities": "Қызметтер",
    "nav.about": "Біз туралы",
    "nav.testimonials": "Пікірлер",
    "nav.conference": "Конференц-зал",
    "nav.contacts": "Байланыс",
    "nav.news": "Жаңалықтар",
    "nav.book": "Брондау",
    "nav.restaurant": "Мейрамхана",
    "nav.sports": "Спорт командалары",
    "nav.offices": "Кеңсе",
    "nav.photoshoots": "Фотосессиялар",

    "hero.title": "Қызыл Жар",
    "hero.subtitle": "Қала жүрегіндегі сәнді демалыс",
    "hero.checkin": "Келу",
    "hero.checkout": "Кету",
    "hero.guests": "Қонақтар",
    "hero.guests_plural": "қонақ",
    "hero.check_availability": "Тексеру",
    "hero.select_date": "Күнді таңдаңыз",

    "about.title": "Қош келдіңіз",
    "about.subtitle": "Сәнділік пен қонақжайлылық",
    "about.heritage.title": "Мұра",
    "about.heritage.desc": "15 жылдан астам тәжірибе.",
    "about.excellence.title": "Керемет",
    "about.excellence.desc": "Әрбір бөлшек ойластырылған.",
    "about.location.title": "Орналасуы",
    "about.location.desc": "Қала орталығында.",
    "about.stats.rooms": "Бөлмелер",
    "about.stats.guests": "Қонақтар",
    "about.stats.rating": "Рейтинг",
    "about.stats.experience": "Жылдар",

    "tour.label": "ВИРТУАЛДЫ ТУР",
    "tour.title": "Қонақүй бойынша 3D тур",
    "tour.desc": "Үйден шықпай-ақ біздің қонақүйдің атмосферасын сезініңіз.",
    "tour.fullscreen": "Толық экран",
    "tour.open_full": "3D турды толық экранда ашу",

    "rooms.title": "Бөлмелер",
    "rooms.subtitle": "Өз бөлмеңізді таңдаңыз",
    "rooms.from": "бастап",
    "rooms.night": "түн",
    "rooms.details": "Толығырақ",
    "rooms.smoking.title": "Темекі шегу ережесі",
    "rooms.smoking.desc": "Бөлмеде темекі шегуге болмайды.",

    "amenities.title": "Қызметтер",
    "amenities.subtitle": "Сіздің жайлылығыңыз үшін",
    "amenities.parking": "Автотұрақ",
    "amenities.parking.desc": "Күзетілетін тұрақ",
    "amenities.restaurant": "Мейрамхана",
    "amenities.restaurant.desc": "Дәмді тағамдар",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Жылдам интернет",
    "amenities.taxi": "Такси",
    "amenities.taxi.desc": "Трансфер қызметі",
    "amenities.spa": "Спа",
    "amenities.spa.desc": "Демалыс",
    "amenities.pool": "Бассейн",
    "amenities.pool.desc": "Жабық бассейн",
    "amenities.coffee": "Кофехана",
    "amenities.coffee.desc": "Жаңа кофе",
    "amenities.business": "Бизнес",
    "amenities.business.desc": "Кездесулер үшін",

    // --- Services Page (KZ) ---
    "services.title": "Қосымша қызметтер",
    "services.photoshoot.text": "Люкс нөмірлерінде фотосессия өткізу: 1 сағат - 15 000 теңге",

    // --- Sports Teams Section (KZ) ---
    "sports.title": "Спорт командаларына",
    "sports.subtitle": "Кәсіби спортшыларға арнайы шарттар",
    "sports.description": "Біз спорт командаларының қажеттіліктерін түсінеміз. Арнайы бағалар, бейімделген тамақтану және жаттығу ыңғайлылықтарын ұсынамыз.",
    "sports.hockey": "Хоккей командалары",
    "sports.hockey.desc": "Хоккейшілерге арнайы шарттар",
    "sports.football": "Футбол командалары",
    "sports.football.desc": "Футбол клубтарын орналастыру",
    "sports.other": "Басқа спорт түрлері",
    "sports.other.desc": "Әр командаға жеке көзқарас",
    "sports.discount": "жеңілдік",
    "sports.contact": "Менеджермен байланысу",
    "sports.features.nutrition": "Спорттық тамақтану",
    "sports.features.schedule": "Икемді тамақтану кестесі",
    "sports.features.transport": "Топтық трансфер",
    "sports.features.meeting": "Жиналыс бөлмелері",

    "testimonials.title": "Пікірлер",
    "testimonials.subtitle": "Қонақтарымыздың пікірлері",

    "conference.title": "Конференц-зал",
    "conference.subtitle": "Іс-шараларға арналған орын",
    "conference.description": "Семинарлар мен тренингтерге арналған.",
    "conference.capacity": "Сыйымдылығы",
    "conference.capacity.value": "150 адамға дейін",
    "conference.people": "адам",
    "conference.equipment": "Жабдықтар",
    "conference.equipment.projector": "Проектор",
    "conference.equipment.sound": "Дыбыс жүйесі",
    "conference.equipment.wifi": "Wi-Fi",
    "conference.equipment.climate": "Климат-бақылау",
    "conference.pricing": "Құны",
    "conference.pricing.hour": "сағатына",
    "conference.pricing.day": "күніне",
    "conference.book": "Брондау",
    "conference.book.desc": "Толығырақ білу үшін хабарласыңыз",
    "conference.gallery": "Галерея",

    "news.title": "Жаңалықтар",
    "news.subtitle": "Соңғы оқиғалар",
    "news.read_more": "Толығырақ",
    "news.category.restaurant": "Мейрамхана",
    "news.category.hotel": "Қонақүй",
    "news.category.events": "Оқиғалар",
    "news.category.conference": "Конференция",
    "news.category.video": "Бейне",

    "news.2gis.title": "Қызыл Жар кешені 2GIS Awards сыйлығын алды",
    "news.2gis.desc": "Сіздердің пікірлеріңіздің арқасында біз үздіктер қатарындамыз.",
    "news.promo.title": "Қызыл Жар ТК: Қош келдіңіздер!",
    "news.promo.desc": "Қонақүй кешенінің жылуы мен жайлылық атмосферасына қош келдіңіздер.",
    "news.buffet.title": "«Буфет» кафесі ашылды",
    "news.buffet.desc": "Жаңартылған мәзірі бар жаңа кафемізге шақырамыз.",
    "news.welcome.title": "Қызыл Жарға қош келдіңіз",
    "news.welcome.desc": "Заманауи жайлылық пен дәстүрлі қонақжайлылықтың үйлесімі.",
    "news.cozy.title": "Жылулық пен жайлылық атмосферасы",
    "news.cozy.desc": "Біз әр қонақ өзін үйдегідей сезінетін жағдай жасаймыз.",
    "news.photo.title": "Қонақүйдің жаңа фотосессиясы",
    "news.photo.desc": "Отелімізге жаңаша көзқарас. Интерьерлердің жаңартылған галереясы.",
    "news.lux317.title": "Арнайы қонақтарға арналған Люкс 317",
    "news.lux317.desc": "Біздің ең жақсы Люкс санатындағы нөмірімізге шолу.",

    "contacts.title": "Байланыс",
    "contacts.subtitle": "Бізбен хабарласыңыз",
    "contacts.info.title": "Байланыс ақпараты",
    "contacts.address.label": "Мекенжай",
    "contacts.phone.label": "Телефон",
    "contacts.email.label": "Email",
    "contacts.hours.label": "Жұмыс уақыты",
    "contacts.form.title": "Бізге жазыңыз",
    "contacts.form.name": "Атыңыз",
    "contacts.form.email": "Email",
    "contacts.form.subject": "Тақырып",
    "contacts.form.message": "Хабарлама",
    "contacts.form.send": "Жіберу",
    "contacts.map.title": "Картада",

    "footer.contact": "Байланыс",
    "footer.links": "Сілтемелер",
    "footer.hours": "Жұмыс уақыты",
    "footer.address": "Петропавл қ., Конституция к. 54",
    "footer.reception.label": "Ресепшн",
    "footer.reception.value": "Тәулік бойы",
    "footer.checkin.label": "Келу / Кету",
    "footer.rights": "Барлық құқықтар қорғалған",
    "footer.privacy": "Құпиялылық",
    "footer.terms": "Ережелер",
    "footer.description": "Сіздің жайлылығыңыз — біздің басымдығымыз.",

    "booking.title": "Брондау",
    "booking.subtitle": "WhatsApp арқылы хабарласамыз",
    "booking.name": "Атыңыз",
    "booking.name.placeholder": "Енгізіңіз",
    "booking.room_type": "Бөлме",
    "booking.select_room": "Таңдаңыз",
    "booking.send": "Жіберу",
    "booking.book_this_room": "Бөлмені брондау",

    "room.amenity.single_bed": "Бір орынды төсек",
    "room.amenity.double_bed": "Екі орынды төсек",
    "room.amenity.queen_bed": "Queen төсек",
    "room.amenity.king_bed": "King төсек",
    "room.amenity.sofa_bed": "Диван",
    "room.amenity.hairdryer": "Фен",
    "room.amenity.workspace": "Жұмыс орны",
    "room.amenity.bathrobe": "Халат",
    "room.amenity.minibar": "Мини-бар",
    "room.amenity.safe": "Сейф",

    "rooms.single_econom.name": "Бір орынды эконом",
    "rooms.single_econom.desc": "Бір қонаққа арналған шағын бөлме.",
    "rooms.single_econom_wide.name": "Кең төсекті эконом",
    "rooms.single_econom_wide.desc": "Жайлы ұйқы үшін кеңейтілген төсегі бар эконом бөлме.",
    "rooms.single_two_room.name": "Бір орынды Екі бөлмелі",
    "rooms.single_two_room.desc": "Бір қонаққа арналған екі бөлмеден тұратын кең нөмір.",
    "rooms.econom_plus.name": "Эконом плюс",
    "rooms.econom_plus.desc": "Қосымша кеңістігі бар жақсартылған эконом.",
    "rooms.single_standard.name": "Бір орынды Стандарт",
    "rooms.single_standard.desc": "Барлық қолайлы жағдайлары бар классикалық бөлме.",
    "rooms.single_semilux.name": "Бір орынды Жартылай люкс",
    "rooms.single_semilux.desc": "Жайлылығы жоғарылатылған бөлме.",
    "rooms.double_econom.name": "Екі орынды эконом",
    "rooms.double_econom.desc": "Екі қонаққа арналған тиімді шешім.",
    "rooms.double_econom_plus.name": "Екі орынды эконом+",
    "rooms.double_econom_plus.desc": "Заманауи дизайны бар кең бөлме.",
    "rooms.double_standard.name": "Екі орынды стандарт",
    "rooms.double_standard.desc": "Сапалы жөндеуден өткен жайлы бөлме.",
    "rooms.triple_econom.name": "Үш орынды эконом",
    "rooms.triple_econom.desc": "Үш адамдық топқа арналған бюджеттік нұсқа.",
    "rooms.triple.name": "Үш орынды жақсартылған",
    "rooms.triple.desc": "Үш жатын орны бар жайлы бөлме.",
    "rooms.quadruple_econom.name": "Төрт орынды эконом",
    "rooms.quadruple_econom.desc": "Үлкен компания немесе отбасы үшін өте қолайлы.",
    "rooms.double_semilux.name": "Екі орынды жартылай люкс",
    "rooms.double_semilux.desc": "Екі адамға арналған демалыс аймағы бар стильді бөлме.",
    "rooms.lux_2room.name": "Екі бөлмелі люкс",
    "rooms.lux_2room.desc": "Жеке жатын бөлмесі және қонақ бөлмесі бар нөмір.",
    "rooms.lux_3room.name": "Үш бөлмелі люкс",
    "rooms.lux_3room.desc": "Үш бөлме, максималды жайлылық.",
    "rooms.family_3room.name": "Отбасылық (3 бөлме)",
    "rooms.family_3room.desc": "Үлкен отбасылық нөмір, балалы ата-аналарға ыңғайлы.",
    "rooms.family_2place.name": "Отбасылық (2 орын)",
    "rooms.family_2place.desc": "Жайлы отбасылық нөмір.",
  },

  // =================================================================================================
  // АНГЛИЙСКИЙ (EN)
  // =================================================================================================
  en: {
    "nav.home": "Home",
    "nav.rooms": "Rooms",
    "nav.amenities": "Amenities",
    "nav.about": "About",
    "nav.testimonials": "Reviews",
    "nav.conference": "Conference Hall",
    "nav.contacts": "Contacts",
    "nav.news": "News",
    "nav.book": "Book Now",
    "nav.restaurant": "Restaurant",
    "nav.sports": "Sports Teams",
    "nav.offices": "Offices",
    "nav.photoshoots": "Photoshoots",

    "hero.title": "Kyzyl Zhar",
    "hero.subtitle": "Exquisite stay in the city heart",
    "hero.checkin": "Check-in",
    "hero.checkout": "Check-out",
    "hero.guests": "Guests",
    "hero.guests_plural": "guests",
    "hero.check_availability": "Check Availability",
    "hero.select_date": "Select Date",

    "about.title": "Welcome",
    "about.subtitle": "Luxury meets hospitality",
    "about.heritage.title": "Heritage",
    "about.heritage.desc": "Over 15 years of experience.",
    "about.excellence.title": "Excellence",
    "about.excellence.desc": "Every detail matters.",
    "about.location.title": "Location",
    "about.location.desc": "In the city center.",
    "about.stats.rooms": "Rooms",
    "about.stats.guests": "Guests",
    "about.stats.rating": "Rating",
    "about.stats.experience": "Years",

    "tour.label": "VIRTUAL TOUR",
    "tour.title": "3D Hotel Tour",
    "tour.desc": "Immerse yourself in our hotel's atmosphere without leaving home.",
    "tour.fullscreen": "Full Screen",
    "tour.open_full": "Open 3D Tour Full Screen",

    "rooms.title": "Rooms & Prices",
    "rooms.subtitle": "Choose your perfect room",
    "rooms.from": "from",
    "rooms.night": "night",
    "rooms.details": "Details",
    "rooms.smoking.title": "Smoking Policy",
    "rooms.smoking.desc": "No smoking in rooms.",

    "rooms.single_econom.name": "Single Economy",
    "rooms.single_econom.desc": "Compact room for budget solo travelers.",
    "rooms.single_econom_wide.name": "Single Economy (Wide Bed)",
    "rooms.single_econom_wide.desc": "Cozy economy room with an enlarged bed.",
    "rooms.single_two_room.name": "Single Two-Room Suite",
    "rooms.single_two_room.desc": "Spacious two-room suite for one guest.",
    "rooms.econom_plus.name": "Economy Plus",
    "rooms.econom_plus.desc": "Improved economy with extra space.",
    "rooms.single_standard.name": "Single Standard",
    "rooms.single_standard.desc": "Classic single room with all amenities.",
    "rooms.single_semilux.name": "Single Semi-Lux",
    "rooms.single_semilux.desc": "Enhanced comfort for one guest.",
    "rooms.double_econom.name": "Double Economy",
    "rooms.double_econom.desc": "Great value for two guests.",
    "rooms.double_econom_plus.name": "Double Economy+",
    "rooms.double_econom_plus.desc": "Spacious room with modern design.",
    "rooms.double_standard.name": "Double Standard",
    "rooms.double_standard.desc": "Comfortable room with quality renovation.",
    "rooms.triple_econom.name": "Triple Economy",
    "rooms.triple_econom.desc": "Budget option for a group of three.",
    "rooms.triple.name": "Triple Improved",
    "rooms.triple.desc": "Comfortable room with three beds.",
    "rooms.quadruple_econom.name": "Quadruple Economy",
    "rooms.quadruple_econom.desc": "Perfect for a large group or family.",
    "rooms.double_semilux.name": "Double Semi-Lux",
    "rooms.double_semilux.desc": "Stylish room with a seating area for two.",
    "rooms.lux_2room.name": "Two-Room Luxury Suite",
    "rooms.lux_2room.desc": "Suite with a separate bedroom and living room.",
    "rooms.lux_3room.name": "Three-Room Luxury Suite",
    "rooms.lux_3room.desc": "Royal scale: three rooms, maximum comfort.",
    "rooms.family_3room.name": "Family (3 Rooms)",
    "rooms.family_3room.desc": "Large family suite, convenient for parents with children.",
    "rooms.family_2place.name": "Family (2 Places)",
    "rooms.family_2place.desc": "Cozy family room.",

    "amenities.title": "Amenities",
    "amenities.subtitle": "For your comfort",
    "amenities.parking": "Parking",
    "amenities.parking.desc": "Secure parking",
    "amenities.restaurant": "Restaurant",
    "amenities.restaurant.desc": "Fine dining",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "High speed",
    "amenities.taxi": "Taxi",
    "amenities.taxi.desc": "Transfer service",
    "amenities.spa": "Spa",
    "amenities.spa.desc": "Relaxation",
    "amenities.pool": "Pool",
    "amenities.pool.desc": "Indoor pool",
    "amenities.coffee": "Coffee",
    "amenities.coffee.desc": "Fresh coffee",
    "amenities.business": "Business",
    "amenities.business.desc": "Meeting center",

    // --- Services Page (EN) ---
    "services.title": "Additional Services",
    "services.photoshoot.text": "Photoshoots in luxury rooms: 1 hour - 15,000 KZT",

    // --- Sports Teams Section (EN) ---
    "sports.title": "For Sports Teams",
    "sports.subtitle": "Special conditions for professional athletes",
    "sports.description": "We understand the needs of sports teams. We offer special prices, adapted nutrition and training facilities.",
    "sports.hockey": "Hockey Teams",
    "sports.hockey.desc": "Special conditions for hockey players",
    "sports.football": "Football Teams",
    "sports.football.desc": "Accommodation for football clubs",
    "sports.other": "Other Sports",
    "sports.other.desc": "Individual approach to each team",
    "sports.discount": "discount",
    "sports.contact": "Contact Manager",
    "sports.features.nutrition": "Sports Nutrition",
    "sports.features.schedule": "Flexible Meal Schedule",
    "sports.features.transport": "Group Transfer",
    "sports.features.meeting": "Meeting Rooms",

    "testimonials.title": "Reviews",
    "testimonials.subtitle": "What guests say about us",

    "conference.title": "Conference Hall",
    "conference.subtitle": "Space for your events",
    "conference.description": "Modern hall for seminars.",
    "conference.capacity": "Capacity",
    "conference.capacity.value": "up to 150 people",
    "conference.people": "people",
    "conference.equipment": "Equipment",
    "conference.equipment.projector": "Projector",
    "conference.equipment.sound": "Sound system",
    "conference.equipment.wifi": "Wi-Fi",
    "conference.equipment.climate": "AC",
    "conference.pricing": "Pricing",
    "conference.pricing.hour": "per hour",
    "conference.pricing.day": "per day",
    "conference.book": "Book Hall",
    "conference.book.desc": "Contact us for details",
    "conference.gallery": "Gallery",

    "news.title": "News",
    "news.subtitle": "Latest events",
    "news.read_more": "Read more",
    "news.category.restaurant": "Restaurant",
    "news.category.hotel": "Hotel",
    "news.category.events": "Events",
    "news.category.conference": "Conference",
    "news.category.video": "Video",

    "news.2gis.title": "Kyzyl Zhar received 2GIS Awards",
    "news.2gis.desc": "Thanks to your reviews, we became one of the best.",
    "news.promo.title": "Kyzyl Zhar: Welcome!",
    "news.promo.desc": "Welcome to the atmosphere of warmth and hospitality.",
    "news.buffet.title": "Buffet Cafe Opening",
    "news.buffet.desc": "We invite you to our new cafe with an updated menu.",
    "news.welcome.title": "Welcome to Kyzyl Zhar",
    "news.welcome.desc": "Unique combination of modern comfort and tradition.",
    "news.cozy.title": "Atmosphere of Warmth",
    "news.cozy.desc": "We create conditions where every guest feels at home.",
    "news.photo.title": "New Hotel Photoshoot",
    "news.photo.desc": "Take a fresh look at our hotel. Updated interior gallery.",
    "news.lux317.title": "Lux 317 for Special Guests",
    "news.lux317.desc": "Exclusive review of our best Luxury suite.",

    "contacts.title": "Contacts",
    "contacts.subtitle": "Get in touch",
    "contacts.info.title": "Contact Info",
    "contacts.address.label": "Address",
    "contacts.phone.label": "Phone",
    "contacts.email.label": "Email",
    "contacts.hours.label": "Working Hours",
    "contacts.form.title": "Write to us",
    "contacts.form.name": "Name",
    "contacts.form.email": "Email",
    "contacts.form.subject": "Subject",
    "contacts.form.message": "Message",
    "contacts.form.send": "Send",
    "contacts.map.title": "Find us",

    "footer.contact": "Contacts",
    "footer.links": "Links",
    "footer.hours": "Working Hours",
    "footer.address": "54 Constitution St, Petropavlovsk",
    "footer.reception.label": "Reception",
    "footer.reception.value": "24/7",
    "footer.checkin.label": "Check-in / Out",
    "footer.rights": "All rights reserved",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.description": "Your comfort is our priority.",

    "booking.title": "Booking",
    "booking.subtitle": "We will contact you via WhatsApp",
    "booking.name": "Name",
    "booking.name.placeholder": "Enter name",
    "booking.room_type": "Room",
    "booking.select_room": "Select room",
    "booking.send": "Send",
    "booking.book_this_room": "Book this room",

    "room.amenity.single_bed": "Single Bed",
    "room.amenity.double_bed": "Double Bed",
    "room.amenity.queen_bed": "Queen Bed",
    "room.amenity.king_bed": "King Bed",
    "room.amenity.sofa_bed": "Sofa Bed",
    "room.amenity.hairdryer": "Hairdryer",
    "room.amenity.workspace": "Work Desk",
    "room.amenity.bathrobe": "Bathrobe",
    "room.amenity.minibar": "Minibar",
    "room.amenity.safe": "Safe",
  },

  // =================================================================================================
  // КИТАЙСКИЙ (ZH)
  // =================================================================================================
  zh: {
    "nav.home": "首页",
    "nav.rooms": "客房",
    "nav.amenities": "设施",
    "nav.about": "关于我们",
    "nav.testimonials": "评论",
    "nav.conference": "会议厅",
    "nav.contacts": "联系我们",
    "nav.news": "新闻",
    "nav.book": "预订",
    "nav.restaurant": "餐厅",
    "nav.sports": "运动队",
    "nav.offices": "办公室",
    "nav.photoshoots": "摄影",

    "hero.title": "克孜勒扎尔",
    "hero.subtitle": "市中心的精致休闲",
    "hero.checkin": "入住",
    "hero.checkout": "退房",
    "hero.guests": "客人",
    "hero.guests_plural": "位客人",
    "hero.check_availability": "查询空房",
    "hero.select_date": "选择日期",

    "about.title": "欢迎",
    "about.subtitle": "奢华与待客之道",
    "about.heritage.title": "传承",
    "about.heritage.desc": "15年经验。",
    "about.excellence.title": "卓越",
    "about.excellence.desc": "细节决定成败。",
    "about.location.title": "位置",
    "about.location.desc": "市中心。",
    "about.stats.rooms": "客房",
    "about.stats.guests": "客人",
    "about.stats.rating": "评分",
    "about.stats.experience": "年",

    "tour.label": "虚拟旅游",
    "tour.title": "酒店3D游览",
    "tour.desc": "无需离开家即可沉浸在我们酒店的氛围中。",
    "tour.fullscreen": "全屏",
    "tour.open_full": "全屏打开3D游览",

    "rooms.title": "客房与价格",
    "rooms.subtitle": "选择您的理想客房",
    "rooms.from": "起价",
    "rooms.night": "晚",
    "rooms.details": "详情",
    "rooms.smoking.title": "吸烟政策",
    "rooms.smoking.desc": "客房内禁烟。",

    "rooms.single_econom.name": "单人经济房",
    "rooms.single_econom.desc": "适合预算独行旅客的紧凑型客房。",
    "rooms.single_econom_wide.name": "单人经济房（宽床）",
    "rooms.single_econom_wide.desc": "带加大床铺的舒适经济房。",
    "rooms.single_two_room.name": "单人两室套房",
    "rooms.single_two_room.desc": "供一位客人使用的宽敞两室套房。",
    "rooms.econom_plus.name": "经济+",
    "rooms.econom_plus.desc": "空间更大的改良经济房。",
    "rooms.single_standard.name": "单人标准房",
    "rooms.single_standard.desc": "设施齐全的经典单人房。",
    "rooms.single_semilux.name": "单人半豪华房",
    "rooms.single_semilux.desc": "舒适度升级的客房。",
    "rooms.double_econom.name": "双人经济房",
    "rooms.double_econom.desc": "两位客人的超值选择。",
    "rooms.double_econom_plus.name": "双人经济+",
    "rooms.double_econom_plus.desc": "现代设计的宽敞客房。",
    "rooms.double_standard.name": "双人标准房",
    "rooms.double_standard.desc": "装修优质的舒适客房。",
    "rooms.triple_econom.name": "三人经济房",
    "rooms.triple_econom.desc": "三人团体的预算选择。",
    "rooms.triple.name": "三人改良房",
    "rooms.triple.desc": "带三张床的舒适客房。",
    "rooms.quadruple_econom.name": "四人经济房",
    "rooms.quadruple_econom.desc": "大型团体或家庭的理想选择。",
    "rooms.double_semilux.name": "双人半豪华房",
    "rooms.double_semilux.desc": "带休息区的时尚客房。",
    "rooms.lux_2room.name": "两室豪华套房",
    "rooms.lux_2room.desc": "带独立卧室和客厅的套房。",
    "rooms.lux_3room.name": "三室豪华套房",
    "rooms.lux_3room.desc": "皇家规模：三间客房，极致舒适。",
    "rooms.family_3room.name": "家庭房（3室）",
    "rooms.family_3room.desc": "大型家庭套房，适合带孩子的父母。",
    "rooms.family_2place.name": "家庭房（2位）",
    "rooms.family_2place.desc": "舒适的家庭客房。",

    "amenities.title": "设施",
    "amenities.subtitle": "为您舒适",
    "amenities.parking": "停车场",
    "amenities.parking.desc": "安全停车",
    "amenities.restaurant": "餐厅",
    "amenities.restaurant.desc": "美食",
    "amenities.wifi": "无线网",
    "amenities.wifi.desc": "高速网络",
    "amenities.taxi": "出租车",
    "amenities.taxi.desc": "接送服务",
    "amenities.spa": "水疗",
    "amenities.spa.desc": "按摩",
    "amenities.pool": "游泳池",
    "amenities.pool.desc": "室内泳池",
    "amenities.coffee": "咖啡",
    "amenities.coffee.desc": "新鲜咖啡",
    "amenities.business": "商务",
    "amenities.business.desc": "会议中心",

    // --- Services Page (ZH) ---
    "services.title": "附加服务",
    "services.photoshoot.text": "豪华客房摄影：1小时 - 15,000 坚戈",

    // --- Sports Teams Section (ZH) ---
    "sports.title": "运动队专属",
    "sports.subtitle": "为专业运动员提供特别条件",
    "sports.description": "我们了解运动队的需求。提供特别价格、定制营养和训练设施。",
    "sports.hockey": "冰球队",
    "sports.hockey.desc": "冰球运动员专属条件",
    "sports.football": "足球队",
    "sports.football.desc": "足球俱乐部住宿",
    "sports.other": "其他运动",
    "sports.other.desc": "每支球队的个性化服务",
    "sports.discount": "折扣",
    "sports.contact": "联系经理",
    "sports.features.nutrition": "运动营养",
    "sports.features.schedule": "灵活用餐时间",
    "sports.features.transport": "团队接送",
    "sports.features.meeting": "会议室",

    "testimonials.title": "评论",
    "testimonials.subtitle": "客人对我们的评价",

    "conference.title": "会议厅",
    "conference.subtitle": "活动空间",
    "conference.description": "现代会议室。",
    "conference.capacity": "容量",
    "conference.capacity.value": "最多150人",
    "conference.people": "人",
    "conference.equipment": "设备",
    "conference.equipment.projector": "投影仪",
    "conference.equipment.sound": "音响",
    "conference.equipment.wifi": "无线网",
    "conference.equipment.climate": "空调",
    "conference.pricing": "价格",
    "conference.pricing.hour": "每小时",
    "conference.pricing.day": "全天",
    "conference.book": "预订",
    "conference.book.desc": "联系我们",
    "conference.gallery": "画廊",

    "news.title": "新闻",
    "news.subtitle": "最新动态",
    "news.read_more": "阅读更多",
    "news.category.restaurant": "餐厅",
    "news.category.hotel": "酒店",
    "news.category.events": "活动",
    "news.category.conference": "会议",
    "news.category.video": "视频",

    "news.2gis.title": "克孜勒扎尔荣获2GIS奖",
    "news.2gis.desc": "感谢您的评价，我们成为了最佳之一。",
    "news.promo.title": "克孜勒扎尔：欢迎！",
    "news.promo.desc": "欢迎来到温暖好客的氛围。",
    "news.buffet.title": "自助餐厅开业",
    "news.buffet.desc": "我们邀请您光临菜单更新的新咖啡厅。",
    "news.welcome.title": "欢迎来到克孜勒扎尔",
    "news.welcome.desc": "现代舒适与传统的独特结合。",
    "news.cozy.title": "温暖舒适的氛围",
    "news.cozy.desc": "我们创造让每位客人都宾至如归的条件。",
    "news.photo.title": "新酒店摄影",
    "news.photo.desc": "以全新视角审视我们的酒店。更新的内饰画廊。",
    "news.lux317.title": "尊贵客人的豪华317",
    "news.lux317.desc": "我们最佳豪华套房的独家评测。",

    "contacts.title": "联系我们",
    "contacts.subtitle": "我们随时联系",
    "contacts.info.title": "联系信息",
    "contacts.address.label": "地址",
    "contacts.phone.label": "电话",
    "contacts.email.label": "电子邮件",
    "contacts.hours.label": "工作时间",
    "contacts.form.title": "写信给我们",
    "contacts.form.name": "您的姓名",
    "contacts.form.email": "电子邮件",
    "contacts.form.subject": "主题",
    "contacts.form.message": "留言",
    "contacts.form.send": "发送",
    "contacts.map.title": "我们在地图上",

    "footer.contact": "联系",
    "footer.links": "链接",
    "footer.hours": "工作时间",
    "footer.address": "彼得罗巴甫洛夫斯克市宪法街54号",
    "footer.reception.label": "前台",
    "footer.reception.value": "24小时",
    "footer.checkin.label": "入住/退房",
    "footer.rights": "版权所有",
    "footer.privacy": "隐私",
    "footer.terms": "条款",
    "footer.description": "您的舒适是我们的首要任务。",

    "booking.title": "预订",
    "booking.subtitle": "我们将通过WhatsApp联系",
    "booking.name": "姓名",
    "booking.name.placeholder": "输入姓名",
    "booking.room_type": "房型",
    "booking.select_room": "选择房间",
    "booking.send": "发送",
    "booking.book_this_room": "预订此房",

    "room.amenity.single_bed": "单人床",
    "room.amenity.double_bed": "双人床",
    "room.amenity.queen_bed": "大床",
    "room.amenity.king_bed": "特大床",
    "room.amenity.sofa_bed": "沙发床",
    "room.amenity.hairdryer": "吹风机",
    "room.amenity.workspace": "工作区",
    "room.amenity.bathrobe": "浴袍",
    "room.amenity.minibar": "迷你吧",
    "room.amenity.safe": "保险箱",
  },

  // =================================================================================================
  // АЗЕРБАЙДЖАНСКИЙ (AZ)
  // =================================================================================================
  az: {
    "nav.home": "Ana səhifə",
    "nav.rooms": "Otaqlar",
    "nav.amenities": "Xidmətlər",
    "nav.about": "Haqqımızda",
    "nav.testimonials": "Rəylər",
    "nav.conference": "Konfrans zalı",
    "nav.contacts": "Əlaqə",
    "nav.news": "Xəbərlər",
    "nav.book": "Rezervasiya",
    "nav.restaurant": "Restoran",
    "nav.sports": "İdman",
    "nav.offices": "Ofislər",
    "nav.photoshoots": "Fotosessiya",

    "hero.title": "Kızıl Jar",
    "hero.subtitle": "Şəhər mərkəzində zərif istirahət",
    "hero.checkin": "Giriş",
    "hero.checkout": "Çıxış",
    "hero.guests": "Qonaqlar",
    "hero.guests_plural": "qonaq",
    "hero.check_availability": "Yoxla",
    "hero.select_date": "Tarix seçin",

    "about.title": "Xoş gəlmisiniz",
    "about.subtitle": "Lüks və qonaqpərvərlik",
    "about.heritage.title": "Miras",
    "about.heritage.desc": "15 ildən çox təcrübə.",
    "about.excellence.title": "Mükəmməllik",
    "about.excellence.desc": "Hər detal düşünülüb.",
    "about.location.title": "Yerləşmə",
    "about.location.desc": "Şəhər mərkəzində.",
    "about.stats.rooms": "Otaqlar",
    "about.stats.guests": "Qonaqlar",
    "about.stats.rating": "Reytinq",
    "about.stats.experience": "İl",

    "tour.label": "VİRTUAL TUR",
    "tour.title": "Otel üzrə 3D Tur",
    "tour.desc": "Evdən çıxmadan otelimizin atmosferinə dalın.",
    "tour.fullscreen": "Tam Ekran",
    "tour.open_full": "3D Turu tam ekranda aç",

    "rooms.title": "Otaqlar",
    "rooms.subtitle": "Otağınızı seçin",
    "rooms.from": "başlayaraq",
    "rooms.night": "gecə",
    "rooms.details": "Ətraflı",
    "rooms.smoking.title": "Siqaret Qaydası",
    "rooms.smoking.desc": "Otaqlarda siqaret çəkmək olmaz.",

    "rooms.single_econom.name": "Tək nəfərlik Ekonom",
    "rooms.single_econom.desc": "Büdcəli səyahətçi üçün kompakt otaq.",
    "rooms.single_econom_wide.name": "Tək nəfərlik Ekonom (Geniş)",
    "rooms.single_econom_wide.desc": "Geniş çarpayılı rahat ekonom otaq.",
    "rooms.single_two_room.name": "Tək nəfərlik İki otaqlı",
    "rooms.single_two_room.desc": "Bir qonaq üçün iki otaqlı geniş nömrə.",
    "rooms.econom_plus.name": "Ekonom Plus",
    "rooms.econom_plus.desc": "Əlavə sahəsi olan təkmilləşdirilmiş ekonom.",
    "rooms.single_standard.name": "Tək nəfərlik Standart",
    "rooms.single_standard.desc": "Bütün şəraiti olan klassik tək nəfərlik otaq.",
    "rooms.single_semilux.name": "Tək nəfərlik Yarım Lüks",
    "rooms.single_semilux.desc": "Yüksək rahatlıqlı otaq.",
    "rooms.double_econom.name": "İki nəfərlik Ekonom",
    "rooms.double_econom.desc": "İki qonaq üçün sərfəli həll.",
    "rooms.double_econom_plus.name": "İki nəfərlik Ekonom+",
    "rooms.double_econom_plus.desc": "Müasir dizaynlı geniş otaq.",
    "rooms.double_standard.name": "İki nəfərlik Standart",
    "rooms.double_standard.desc": "Keyfiyyətli təmirli rahat otaq.",
    "rooms.triple_econom.name": "Üç nəfərlik Ekonom",
    "rooms.triple_econom.desc": "Üç nəfərlik qrup üçün büdcə variantı.",
    "rooms.triple.name": "Üç nəfərlik Təkmilləşdirilmiş",
    "rooms.triple.desc": "Üç çarpayılı rahat otaq.",
    "rooms.quadruple_econom.name": "Dörd nəfərlik Ekonom",
    "rooms.quadruple_econom.desc": "Böyük şirkət və ya ailə üçün idealdır.",
    "rooms.double_semilux.name": "İki nəfərlik Yarım Lüks",
    "rooms.double_semilux.desc": "İki nəfərlik istirahət zonası olan şık otaq.",
    "rooms.lux_2room.name": "İki otaqlı Lüks",
    "rooms.lux_2room.desc": "Ayrı yataq otağı və qonaq otağı olan nömrə.",
    "rooms.lux_3room.name": "Üç otaqlı Lüks",
    "rooms.lux_3room.desc": "Kral miqyası: üç otaq, maksimum rahatlıq.",
    "rooms.family_3room.name": "Ailəvi (3 otaq)",
    "rooms.family_3room.desc": "Böyük ailə nömrəsi, uşaqlı valideynlər üçün rahatdır.",
    "rooms.family_2place.name": "Ailəvi (2 yer)",
    "rooms.family_2place.desc": "Rahat ailə nömrəsi.",

    "amenities.title": "Xidmətlər",
    "amenities.subtitle": "Sizin rahatlığınız üçün",
    "amenities.parking": "Parkinq",
    "amenities.parking.desc": "Mühafizəli",
    "amenities.restaurant": "Restoran",
    "amenities.restaurant.desc": "Zərif mətbəx",
    "amenities.wifi": "Wi-Fi",
    "amenities.wifi.desc": "Sürətli internet",
    "amenities.taxi": "Taksi",
    "amenities.taxi.desc": "Transfer",
    "amenities.spa": "Spa",
    "amenities.spa.desc": "Masaj",
    "amenities.pool": "Hovuz",
    "amenities.pool.desc": "Qapalı hovuz",
    "amenities.coffee": "Kofe",
    "amenities.coffee.desc": "Təzə kofe",
    "amenities.business": "Biznes",
    "amenities.business.desc": "Görüşlər üçün",

    // --- Services Page (AZ) ---
    "services.title": "Əlavə xidmətlər",
    "services.photoshoot.text": "Lüks otaqlarda fotosessiya: 1 saat - 15 000 tenge",

    // --- Sports Teams Section (AZ) ---
    "sports.title": "İdman komandaları üçün",
    "sports.subtitle": "Peşəkar idmançılar üçün xüsusi şərtlər",
    "sports.description": "Biz idman komandalarının ehtiyaclarını başa düşürük. Xüsusi qiymətlər, uyğunlaşdırılmış qidalanma və məşq imkanları təklif edirik.",
    "sports.hockey": "Xokkey komandaları",
    "sports.hockey.desc": "Xokkeyçilər üçün xüsusi şərtlər",
    "sports.football": "Futbol komandaları",
    "sports.football.desc": "Futbol klublarının yerləşdirilməsi",
    "sports.other": "Digər idman növləri",
    "sports.other.desc": "Hər komandaya fərdi yanaşma",
    "sports.discount": "endirim",
    "sports.contact": "Menecerlə əlaqə",
    "sports.features.nutrition": "İdman qidalanması",
    "sports.features.schedule": "Çevik yemək cədvəli",
    "sports.features.transport": "Qrup transferi",
    "sports.features.meeting": "Görüş otaqları",

    "testimonials.title": "Rəylər",
    "testimonials.subtitle": "Qonaqlarımız nə deyir",

    "conference.title": "Konfrans zalı",
    "conference.subtitle": "Tədbirlər üçün məkan",
    "conference.description": "Müasir zal.",
    "conference.capacity": "Tutum",
    "conference.capacity.value": "150 nəfərə qədər",
    "conference.people": "nəfər",
    "conference.equipment": "Avadanlıq",
    "conference.equipment.projector": "Proyektor",
    "conference.equipment.sound": "Səs sistemi",
    "conference.equipment.wifi": "Wi-Fi",
    "conference.equipment.climate": "Kondisioner",
    "conference.pricing": "Qiymət",
    "conference.pricing.hour": "saatda",
    "conference.pricing.day": "günlük",
    "conference.book": "Rezerv et",
    "conference.book.desc": "Əlaqə saxlayın",
    "conference.gallery": "Qalereya",

    "news.title": "Xəbərlər",
    "news.subtitle": "Son hadisələr",
    "news.read_more": "Ətraflı",
    "news.category.restaurant": "Restoran",
    "news.category.hotel": "Otel",
    "news.category.events": "Tədbirlər",
    "news.category.conference": "Konfrans",
    "news.category.video": "Video",

    "news.2gis.title": "Kızıl Jar 2GIS Mükafatını aldı",
    "news.2gis.desc": "Rəyləriniz sayəsində ən yaxşılardan biri olduq.",
    "news.promo.title": "Kızıl Jar: Xoş gəlmisiniz!",
    "news.promo.desc": "İstilik və qonaqpərvərlik atmosferinə xoş gəlmisiniz.",
    "news.buffet.title": "Bufet kafesi açıldı",
    "news.buffet.desc": "Sizi yenilənmiş menyulu yeni kafemizə dəvət edirik.",
    "news.welcome.title": "Kızıl Jara xoş gəlmisiniz",
    "news.welcome.desc": "Müasir rahatlıq və ənənənin unikal birləşməsi.",
    "news.cozy.title": "İstilik və rahatlıq atmosferi",
    "news.cozy.desc": "Hər qonağın özünü evdəki kimi hiss etdiyi şərait yaradırıq.",
    "news.photo.title": "Yeni Otel Fotosessiyası",
    "news.photo.desc": "Otelimizə yeni bir baxış. Yenilənmiş interyer qalereyası.",
    "news.lux317.title": "Xüsusi qonaqlar üçün Lüks 317",
    "news.lux317.desc": "Ən yaxşı Lüks nömrəmizin eksklüziv icmalı.",

    "contacts.title": "Əlaqə",
    "contacts.subtitle": "Bizimlə əlaqə",
    "contacts.info.title": "Əlaqə məlumatı",
    "contacts.address.label": "Ünvan",
    "contacts.phone.label": "Telefon",
    "contacts.email.label": "Email",
    "contacts.hours.label": "İş saatları",
    "contacts.form.title": "Bizə yazın",
    "contacts.form.name": "Adınız",
    "contacts.form.email": "Email",
    "contacts.form.subject": "Mövzu",
    "contacts.form.message": "Mesaj",
    "contacts.form.send": "Göndər",
    "contacts.map.title": "Xəritə",

    "footer.contact": "Əlaqə",
    "footer.links": "Keçidlər",
    "footer.hours": "İş saatları",
    "footer.address": "Konstitusiya küç. 54, Petropavlovsk",
    "footer.reception.label": "Resepşn",
    "footer.reception.value": "24/7",
    "footer.checkin.label": "Giriş / Çıxış",
    "footer.rights": "Bütün hüquqlar qorunur",
    "footer.privacy": "Məxfilik",
    "footer.terms": "Şərtlər",
    "footer.description": "Rahatlığınız bizim üçün vacibdir.",

    "booking.title": "Rezervasiya",
    "booking.subtitle": "WhatsApp ilə əlaqə saxlayacağıq",
    "booking.name": "Ad",
    "booking.name.placeholder": "Adınızı yazın",
    "booking.room_type": "Otaq",
    "booking.select_room": "Seçin",
    "booking.send": "Göndər",
    "booking.book_this_room": "Rezerv et",

    "room.amenity.single_bed": "Tək çarpayı",
    "room.amenity.double_bed": "İkili çarpayı",
    "room.amenity.queen_bed": "Queen çarpayı",
    "room.amenity.king_bed": "King çarpayı",
    "room.amenity.sofa_bed": "Divan",
    "room.amenity.hairdryer": "Fen",
    "room.amenity.workspace": "İş masası",
    "room.amenity.bathrobe": "Xalat",
    "room.amenity.minibar": "Mini-bar",
    "room.amenity.safe": "Seyf",
  },
};

const languageNames: Record<Language, string> = {
  ru: "Русский",
  kz: "Қазақша",
  en: "English",
  zh: "中文",
  az: "Azərbaycan",
};

const languageFlags: Record<Language, string> = {
  ru: "🇷🇺",
  kz: "🇰🇿",
  en: "🇬🇧",
  zh: "🇨🇳",
  az: "🇦🇿",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("ru");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export { languageNames, languageFlags };